language: go
go:
  - 1.11
  - 1.12
  - 1.13
  - tip

sudo: false

before_install:
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/axw/gocov/gocov

install:
  - go get .
  - go get ./slugify

script:
  - slugify -V
  - slugify abc
  - echo "abc" | slugify
  - echo "abc" > abc.txt && slugify < abc.txt
  - go test
